# Generated by Django 3.2 on 2021-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0002_alter_customers_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='bal',
            field=models.FloatField(),
        ),
    ]
