# Generated by Django 3.2 on 2021-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0003_alter_customers_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=20)),
                ('to_name', models.CharField(max_length=20)),
                ('trans_amt', models.FloatField()),
            ],
        ),
    ]
